# Generated by Django 3.2.9 on 2021-11-17 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': 'blog category', 'verbose_name_plural': 'blog categories'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now, help_text='A slug to identify posts by this category', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
