# Generated by Django 3.2.9 on 2021-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcategoryindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
