# Generated by Django 3.2.9 on 2022-01-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211222_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagetag',
            name='search_image',
        ),
    ]
